### ISSUE TITLE
No Hover Events?

### ISSUE THREAD

**Issue by andrelevi** [vuplex/xrit-webview-example#3]
This demo scene doesn't have working hover events for the UI (this can be seen in the README gif).

The normal world canvas demo scene has working hover events, when input is controlled via the mouse.

Is there a way to get hover events to work properly in this example? Thanks

**Comment by BinaryNate** [comment]
Hi, Andre 👋. Thank you for using 3D WebView! The README links to [this article](https://support.vuplex.com/articles/xr-interaction-toolkit), which explains that hover events aren't supported out-of-the-box for XRIT:

> CanvasWebViewPrefab doesn't currently support hover interactions with XRIT.

The reason for this is that Unity doesn't have a standard event for hovering. 3D WebView's DefaultPointerInputDetector.cs script uses a reflection-based hack to try to detect hovering, but it only works for input modules that derive from PointerInputModule like StandaloneInputModule and OVRInputModule, and it doesn't work with XRIT's XRUIInputModule. I'm tracking this issue and added you to its waitlist so that I'll send you an update if this changes in the future. In the meantime, you could potentially implement a custom [IPointerInputDetector](https://developer.vuplex.com/webview/IPointerInputDetector) that detects hovering in XRIT and set it as the CanvasWebViewPrefab's input detector like [described here](https://support.vuplex.com/articles/clicking#custom).
