### ISSUE TITLE
Can CanvasWebViewPrefab be curved?

### ISSUE THREAD

**Issue by wei-kris** [vuplex/xrit-webview-example#9]
I use canvaswebviewprefab, and I want it to be curved.

**Comment by binarynate** [comment]
Hi, @wei-kris 👋. Thank you for using 3D WebView! In the future, for general support, please contact me via the [Vuplex contact page](https://support.vuplex.com/contact), because I only use GitHub for issues specific to the example projects. 3D WebView doesn't have a built-in feature to curve meshes, but I've heard from customers that the 3rd party asset [Curved UI](https://assetstore.unity.com/packages/tools/gui/curved-ui-vr-ready-solution-to-bend-warp-your-canvas-53258) works well for curving a Canvas with a CanvasWebViewPrefab. So, I recommend trying that asset.
